version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/pgsql/data
    env_file:
      - ./server/.env
    ports:
      - 5432:5432
  redis: 
     image: redislabs/redismod
     ports:
       - '6379:6379'
  server:
    build: ./server
    command: sh docker-entrypoint.sh
    volumes:
      - ./server:/server
    ports:
      - 8000:8000
    env_file:
      - ./server/.env
    depends_on:
      - db
      - redis
    links:
      - "db:database"
  celery:
    build: ./server
    command: celery -A config worker -l info
    volumes:
      - ./server:/server:Z
    depends_on:
      - server
    links:
      - "redis:redis"
  flower:
    build:
      context: ./server
    command: celery -A config flower -l info
    volumes:
      - ./server:/server:Z
    ports:
      - 5555:5555
    depends_on:
      - celery