# Generated by Django 4.1 on 2022-10-28 07:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("media_title", models.CharField(max_length=50)),
                ("media_description", models.TextField(max_length=100)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("IMG", "Image"),
                            ("VID", "Video"),
                            ("AUD", "Audio"),
                            (
                                "<class 'advertisement.models.Media.MediaType.Meta'>",
                                "Meta",
                            ),
                        ],
                        default="IMG",
                        max_length=150,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        default="settings.MEDIA_ROOT/videos/placeholder.file",
                        upload_to="videos",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media",
                "verbose_name_plural": "Media",
            },
        ),
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_created=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=255)),
                ("campaigns", models.ManyToManyField(to="management.campaign")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.company",
                    ),
                ),
                ("zone", models.ManyToManyField(to="management.zone")),
            ],
            options={
                "verbose_name": "Advertisement",
                "verbose_name_plural": "Advertisements",
            },
        ),
    ]
