# Generated by Django 4.1 on 2022-10-28 05:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("media_title", models.CharField(max_length=50)),
                ("media_description", models.TextField(max_length=100)),
                (
                    "media_type",
                    models.SmallIntegerField(
                        choices=[
                            ("1", "Image"),
                            ("2", "Video"),
                            ("3", "Audio"),
                            (
                                "<class 'advertisement.models.Media.MediaType.Meta'>",
                                "Meta",
                            ),
                        ],
                        default="1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media",
                "verbose_name_plural": "Media",
            },
        ),
        migrations.DeleteModel(
            name="Audio",
        ),
        migrations.RemoveField(
            model_name="content",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="content",
            name="module",
        ),
        migrations.DeleteModel(
            name="Image",
        ),
        migrations.DeleteModel(
            name="Video",
        ),
        migrations.DeleteModel(
            name="Content",
        ),
    ]
