# Generated by Django 4.1 on 2022-10-28 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
        ("advertisement", "0004_alter_media_media_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="media",
            field=models.ManyToManyField(
                blank=True, null=True, to="advertisement.media"
            ),
        ),
        migrations.AddField(
            model_name="media",
            name="campaigns",
            field=models.ManyToManyField(
                blank=True, null=True, to="management.company"
            ),
        ),
    ]
