# Generated by Django 4.1 on 2022-10-29 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0005_advertisement_media_media_campaigns"),
    ]

    operations = [
        migrations.RenameField(
            model_name="media",
            old_name="media_description",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="media",
            old_name="media_title",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="media",
            old_name="media_type",
            new_name="type",
        ),
    ]
