# Generated by Django 4.1 on 2022-10-29 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0006_rename_media_description_media_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="share_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="media",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
