# Generated by Django 4.1 on 2022-11-02 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0007_media_share_count_media_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="share_count",
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name="media",
            name="view_count",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
