# Generated by Django 4.1 on 2022-11-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
        ("advertisement", "0008_alter_media_share_count_alter_media_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="campaigns",
            field=models.ManyToManyField(
                blank=True, null=True, to="management.campaign"
            ),
        ),
    ]
