# Generated by Django 4.1 on 2022-11-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0009_reward"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="assigned_credits",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
