# Generated by Django 4.1 on 2022-11-28 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0004_remove_company_credits_count_creditoffering_credit_and_more",
        ),
        ("advertisement", "0010_advertisement_assigned_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="per_view_credits",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="advertisement",
            name="assigned_credits",
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.CreateModel(
            name="CreditAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="management.company",
                        verbose_name="",
                    ),
                ),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="advertisement.advertisement",
                        verbose_name="",
                    ),
                ),
            ],
            options={
                "verbose_name": "Credit Assignment",
                "verbose_name_plural": "Credit Assignments",
            },
        ),
    ]
