# Generated by Django 4.1 on 2022-09-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="account",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
