# Generated by Django 4.1 on 2022-09-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_account_is_admin_alter_account_birth_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="address",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
