# Generated by Django 4.1 on 2022-10-06 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_account_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="phone_no",
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
