FROM python:3.8
ENV DockerHome=/server

WORKDIR ${DockerHome}

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1 

RUN pip install --upgrade pip 
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . ${DockerHome}
