# Generated by Django 4.1 on 2022-10-28 07:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=255)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
            ],
            options={
                "verbose_name": "Campaign",
                "verbose_name_plural": "Campaigns",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        auto_created=True, auto_now_add=True, verbose_name="Date Joined"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "web_url",
                    models.URLField(blank=True, null=True, verbose_name="Web Page"),
                ),
                ("is_active", models.BooleanField(verbose_name="Active")),
                ("country", models.CharField(default="Tanzania", max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("street", models.CharField(max_length=50)),
                ("house_no", models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                "verbose_name": "Company",
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        help_text="The Compaign that the Zone Belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
            },
        ),
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_created=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("is_valid", models.BooleanField(default=True)),
                ("count", models.PositiveBigIntegerField(default=200)),
                ("token_value", models.FloatField()),
                (
                    "offered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Token",
                "verbose_name_plural": "Tokens",
            },
        ),
        migrations.AddField(
            model_name="campaign",
            name="company",
            field=models.ForeignKey(
                help_text="Company Running the Campaign",
                on_delete=django.db.models.deletion.CASCADE,
                to="management.company",
            ),
        ),
    ]
