# Generated by Django 4.1 on 2022-10-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="media",
            field=models.ManyToManyField(to="management.media"),
        ),
        migrations.AlterField(
            model_name="media",
            name="media_type",
            field=models.CharField(
                choices=[
                    ("IMG", "Image"),
                    ("VID", "Video"),
                    ("AUD", "Audio"),
                    ("<class 'management.models.Media.MediaType.Meta'>", "Meta"),
                ],
                default="IMG",
                max_length=50,
            ),
        ),
    ]
