# Generated by Django 4.1 on 2022-11-22 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Token",
        ),
    ]
