# Generated by Django 4.1 on 2022-11-25 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_delete_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="credits_count",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
