# Generated by Django 4.1 on 2022-10-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_advertisement_media_alter_media_media_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.CharField(max_length=120),
        ),
    ]
