# Generated by Django 4.1 on 2022-10-23 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_alter_company_date_joined"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="advertisement",
            name="campaigns",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="company",
        ),
        migrations.RemoveField(
            model_name="advertisement",
            name="zone",
        ),
        migrations.DeleteModel(
            name="Media",
        ),
        migrations.RemoveField(
            model_name="company",
            name="address",
        ),
        migrations.AddField(
            model_name="company",
            name="city",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="company",
            name="country",
            field=models.CharField(default="Tanzania", max_length=50),
        ),
        migrations.AddField(
            model_name="company",
            name="house_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="street",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="Advertisement",
        ),
    ]
