# Generated by Django 4.1 on 2022-11-28 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0003_company_credits_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="company",
            name="credits_count",
        ),
        migrations.CreateModel(
            name="CreditOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("on", models.DateTimeField(auto_now_add=True)),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="management.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "credit offering",
                "verbose_name_plural": "credit offerings",
            },
        ),
        migrations.CreateModel(
            name="Credit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intial_value", models.PositiveIntegerField(editable=False)),
                ("current_value", models.PositiveIntegerField(editable=False)),
                (
                    "offered_to",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="management.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "credit",
                "verbose_name_plural": "credits",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="current_credit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="management.credit",
            ),
        ),
    ]
