# Generated by Django 4.1 on 2022-10-28 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0004_alter_zone_campaign"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="file",
            field=models.FileField(
                default="settings.MEDIA_ROOT/videos/placeholder.file",
                upload_to="videos",
            ),
        ),
    ]
