# Generated by Django 4.1 on 2022-11-28 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "management",
            "0004_remove_company_credits_count_creditoffering_credit_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="credit",
            old_name="intial_value",
            new_name="initial_value",
        ),
    ]
