# Generated by Django 4.1 on 2022-10-28 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_alter_company_date_joined"),
        ("management", "0005_media_file"),
    ]

    operations = []
