# Generated by Django 4.1 on 2022-11-28 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0005_rename_intial_value_credit_initial_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditDebt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                ("on", models.DateTimeField(auto_now_add=True)),
                (
                    "to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="management.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "credit offering",
                "verbose_name_plural": "credit offerings",
            },
        ),
    ]
